example_https : sample.o
	$(CC) -pthread -o example_https sample.o

sample.o : sample.c
	$(CC) -c sample.c

#Thread.o : Thread.c
#	$(CC) -c Thread.c

clean :
	rm example_https 


#gcc sample.c -o sample
