example_tcp_client : example_tcp_client.o
	$(CC) -o example_tcp_client example_tcp_client.o

example_tcp_client.o : example_tcp_client.c
	$(CC) -c example_tcp_client.c

#Thread.o : Thread.c
#	$(CC) -c Thread.c

clean :
	rm example_tcp_client example_tcp_client.o


#gcc sample.c -o sample
